Templates homework/level 2
VladimirFalkov/django_templates_challenges pull request #2
Opened 2023-12-08 07:13 UTC by VladimirFalkov

2023-12-10 17:56 UTC, khoshov commented on django_templates_homework/generators/transactions.py
> +        currency=str(random.choice(list(Currency))).split(".")[1],
Вот здесь не понял зачем это

2023-12-10 17:56 UTC, khoshov requested changes
Нет решения четвертого задания

2023-12-10 17:57 UTC, khoshov commented on templates/level_2/transactions_list.html
> +              <tr>
Обрати внимание что должен CSS класс dangerous появляться если can_be_fraud

2023-12-11 13:15 UTC, VladimirFalkov commented on django_templates_homework/generators/transactions.py
> +        currency=str(random.choice(list(Currency))).split(".")[1],
<img width="1728" alt="Снимок экрана 2023-12-11 в 16 13 00" src="https://github.com/VladimirFalkov/django_templates_challenges/assets/64154057/fcf227d9-d259-40ae-ade2-1b22edb28504">
<img width="1347" alt="Снимок экрана 2023-12-11 в 16 14 00" src="https://github.com/VladimirFalkov/django_templates_challenges/assets/64154057/38cf7593-937a-430e-aa64-4273f7695adf">

2023-12-11 13:16 UTC, VladimirFalkov commented on django_templates_homework/generators/transactions.py
> +        currency=str(random.choice(list(Currency))).split(".")[1],
чтоб было красиво

2023-12-13 20:27 UTC, khoshov commented on django_templates_homework/generators/transactions.py
> +        currency=str(random.choice(list(Currency))).split(".")[1],
Видимо это баг задания

2023-12-13 20:28 UTC, khoshov approved these changes

2023-12-14 06:43 UTC, merged